### ISSUE TITLE
你好，咨询一个超时的问题

### ISSUE THREAD

**Issue by loganjing** [JacksonTian/bagpipe#13]
如果一次性异步读取10个文件，设置了超时时间之后，读取了2个文件，后续8个文件确实超时了，但是只是代码上超时了，实际上IO还是去读取了，读取完成之后还是会调用注入的函数，在arguments中还是存在已经读取出来的文件内容，是否有办法终止这些文件的读取？

**Comment by JacksonTian** [comment]
很多操作系统都没提供取消io操作的功能的


发自我的 iPhone

**Comment by loganjing** [comment]
哦，感谢回复。
