### ISSUE TITLE
写错了？

### ISSUE THREAD

**Issue by manooog** [JacksonTian/bagpipe#20]
https://github.com/JacksonTian/bagpipe/blob/6d759c5995cea5a7c49ef4c57588e9f7fccc024d/lib/bagpipe.js#L87

这里为什么是根据这个条件来判断是否`full`的状态啊？？

**Comment by JacksonTian** [comment]
应该是 https://github.com/JacksonTian/bagpipe/commit/ae4bb9f04e7b968507f4981c0ebe9ec385c5161e 引入的问题。
