### ISSUE TITLE
关于文件描述符和数据库连接池

### ISSUE THREAD

**Issue by z3214965** [JacksonTian/bagpipe#22]
你好：
我看到你写的真实案例中提到了文件描述符，我想问下文件描述符和数据库连接池有什么关系没，关于你真实案例中的问题，能不能用数据库连接池解决？

**Comment by JacksonTian** [comment]
文件描述符和数据库连接池没有关系。

数据库连接池解决的问题是创建和销毁连接的开销。

**Comment by z3214965** [comment]
我现在有个项目是打开sqlite，碰到了你真实案例中的问题，我想请问下，打开sqlite是用文件描述符，还是数据库连接池？如果是文件描述符的话，sqlite有没有数据库连接池说法？

**Comment by lilifan** [comment]
是打开 过程 还是 连接 sqlite 过程中遇到问题？   没明白你的问题喔 @z3214965
