### ISSUE TITLE
理解

### ISSUE THREAD

**Issue by menciusKael** [JacksonTian/bagpipe#23]
var bagpipe = new Bagpipe(10);
for (var i = 0; i < 100; i++) {
  bagpipe.push(async, function () {
 
  });
}

如果实际控制时这么写，那本质上是不相当于 Bagpipe维护一个了一个队列，限制并发数为最多10个，然后队列长度为100，10个并发处理完成，下10个进入处理，新任务进入队列，是这么理解么

**Comment by JacksonTian** [comment]
不是。完成一个处理下一个。
