### ISSUE TITLE
排队的任务没有执行

### ISSUE THREAD

**Issue by poype** [JacksonTian/bagpipe#25]
一共有100个任务，Bagpipe的并发数设置为5。后面95个任务在队列排队。但前5个任务执行完成后，后面95个任务都没有执行，一致在阻塞。

**Comment by lilifan** [comment]
应该是你用法不对，基本的使用场景不可能出错的。方便贴下代码吗？ @poype

**Comment by zytxh** [comment]
看源码队列长度超过限制是：
`    // 队列长度也超过限制值时
    if (this.queue.length < this.queueLength || !this.options.refuse) {
      this.queue.push({
        method: method,
        args: args
      });
    } else {
      var err = new Error('Too much async call in queue');
      err.name = 'TooMuchAsyncCallError';
      callback(err);
    }`
只会执行下一个的回调，抛出错误，并不会塞进队列里

**Comment by zytxh** [comment]
> 一共有100个任务，Bagpipe的并发数设置为5。后面95个任务在队列排队。但前5个任务执行完成后，后面95个任务都没有执行，一致在阻塞。

看源码队列长度超过限制是：
```js
  // 队列长度也超过限制值时
    if (this.queue.length < this.queueLength || !this.options.refuse) {
      this.queue.push({
        method: method,
        args: args
      });
    } else {
      var err = new Error('Too much async call in queue');
      err.name = 'TooMuchAsyncCallError';
      callback(err);
    }
```
是不是设置了options.refuse？ @poype

**Comment by JacksonTian** [comment]
应该就是没有正常 callback。
